###^ All Posibles Cases for Departments

###* TEST CASE 1: Obtener todos los departamentos ✔
GET http://localhost:1234/departments



###* TEST CASE 2: Obtener un departamento por nombre ✔
GET http://localhost:1234/departments/name/ventas

###* TEST CASE 2.2: Departamento no encontrado ✔
GET http://localhost:1234/departments/name/departamentoDesconocido



###* TEST CASE 3: Crear un nuevo departamento ✔
POST http://localhost:1234/departments
Content-Type: application/json

{
  "name": "nuevo5",
  "totalEmployees": 20000,
  "description": "Handles all marketing activities."
}


###* TEST CASE 3.3: Crear un departamento con nombre duplicado ✔
POST http://localhost:1234/departments
Content-Type: application/json

{
  "name": "HR",
  "totalEmployees": 5,
  "description": "Duplicate department name."
}




### TODO: verificar porque lo numera diferente en la DB de 988888899900000 a 2147483647
###* TEST CASE 4: Actualizar un departamento ✔
PATCH http://localhost:1234/departments/name/Atención al Cliente
Content-Type: application/json

{
  "name": "hr",
  "totalEmployees": 988888899900000,
  "description": "Updated description for hr"
}


###* TEST CASE 4.4: Actualizar un departamento no encontrado ✔
PATCH http://localhost:1234/departments/name/NonExistenttttttt2
Content-Type: application/json

{
  "name": "NonExistent2",
  "totalEmployees": 0,
  "description": "This department does not exist."
}





###* TEST CASE 5: Eliminar un departamento ✔
DELETE http://localhost:1234/departments/name/nuevo5

###* TEST CASE 5.5: Eliminar un departamento no encontrado ✔
DELETE http://localhost:1234/departments/name/UnknownDepartmenttttt