###! All Posibles Cases for EMPLOYEES

###* TEST CASE 1: obtener todos los empleados ✔
GET http://localhost:1234/employees




###* TEST CASE 2: obtener empleados por departamento ✔
GET http://localhost:1234/employees/department/2

###* TEST CASE 2.2: no hay empleados en departamento existente ❌
###! todavia no
# GET http://localhost:1234/employees/department/4

###* TEST CASE 2.3: departamento no encontrado ✔
GET http://localhost:1234/employees/department/999




###* TEST CASE 3: Obtener empleado por ID ✔
GET http://localhost:1234/employees/id/8-1234-5678

###* TEST CASE 3.3: empleado con ID no encontrado ✔
GET http://localhost:1234/employees/id/8-0000-0000





###* TEST CASE 4: obtener empleado por nombre ✔
GET http://localhost:1234/employees/name/Carlos

###* TEST CASE 4.4: empleado con nombre no encontrado ✔
GET http://localhost:1234/employees/name/Pedro





###* TEST CASE 5: Obtener empleado por username ✔
GET http://localhost:1234/employees/username/carlos.garcia

###* TEST CASE 5.5: empleado con username no encontrado ✔
GET http://localhost:1234/employees/username/pedro.sanchez





###* TEST CASE 6: Crear un nuevo empleado ✔
POST http://localhost:1234/employees
Content-Type: application/json

{
  //hacer phone number unique
  "id": "8-888-8888",
  "first_name": "Luis",
  "second_name": "Antonio",
  "first_lastName": "Salazar",
  "second_lastName": "Mora",
  "age": 29,
  "address": "Calle 10",
  "email": "luis.salazar@example.com",
  "phone_number": "+507 111-2233",
  "hire_date": "2024-07-27",
  "salary": "1900",
  "department": "1",
  "role": "2",
  "username": "luis.salazar"
}





###* TEST CASE 7: Actualizar un empleado ✔
PATCH http://localhost:1234/employees/id/8-888-8888
Content-Type: application/json

{
  "id": "8-888-8888",
  "first_name": "Luissssssss",
  "second_name": "Antonioooooo",
  "first_lastName": "Salazar",
  "second_lastName": "Mora",
  "age": 29,
  "address": "Calle 10",
  "email": "luis.salazar@example.com",
  "phone_number": "+507 111-2233",
  "hire_date": "2024-07-27",
  "salary": "30000",
  "department": "1",
  "role": "2",
  "username": "luis.salazar"
}

###* TEST CASE 7.7: Actualizar empleado que no existe ✔
PATCH http://localhost:1234/employees/id/8-0000-0000
Content-Type: application/json

{
  "id": "8-888-8888",
  "first_name": "Luisssssssssss",
  "second_name": "Antonioaaaaaaaaaaaaaaaaaaaaaa",
  "first_lastName": "Salazar",
  "second_lastName": "Mora",
  "age": 29,
  "address": "Calle 10",
  "email": "luis.salazar@example.com",
  "phone_number": "+507 111-2233",
  "hire_date": "2024-07-27",
  "salary": "30000",
  "department": "1",
  "role": "2",
  "username": "luis.salazar"
}






###* TEST CASE 8: Eliminar un empleado ✔
DELETE http://localhost:1234/employees/id/8-888-8888

###* TEST CASE 8.8: Eliminar empleado que no existe ✔
DELETE http://localhost:1234/employees/id/8-0000-000088
